name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v6
      
      - name: Add timestamp to JS/HTML file versions
        run: |
          TIMESTAMP=$(date +%s)
          echo "Applying timestamp: $TIMESTAMP to .js and .html files"
          find . -type f \( -name "*.js" -o -name "*.html" \) -print0 | while IFS= read -r -d $'\0' FILENAME; do
            echo "Processing $FILENAME"
            sed -i "s/\\?v=/\\?v=$TIMESTAMP/g" "$FILENAME"
          done

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          # Note: The 'Context access might be invalid' warning for secrets is often a false positive
          # in the VS Code extension if it cannot validate the secret existence.
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: 'domain-sonar/'
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            docs/**
